package com.allen.springbootelasticjob.project.dao;

import com.allen.springbootelasticjob.project.model.JobProject;
import com.allen.springbootelasticjob.project.model.JobProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JobProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    long countByExample(JobProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int deleteByExample(JobProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int insert(JobProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int insertSelective(JobProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    List<JobProject> selectByExample(JobProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    JobProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") JobProject record, @Param("example") JobProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int updateByExample(@Param("record") JobProject record, @Param("example") JobProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(JobProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_project
     *
     * @mbg.generated Thu Jun 25 17:47:34 GMT+08:00 2020
     */
    int updateByPrimaryKey(JobProject record);
}